name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master # master 브랜치를 사용할 경우를 대비해 추가

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/img_to_text_api:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    
    steps:
      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/img_to_text_api:latest

      - name: Stop and Remove old container
        continue-on-error: true
        run: docker rm -f img_to_text_api

      - name: Run new container
        run: docker run -d --name img_to_text_api -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/img_to_text_api:latest
